# Generated by Django 4.2.11 on 2024-05-10 08:41

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_name', models.CharField(max_length=50, unique=True)),
                ('category_description', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Stock_Item',
            fields=[
                ('item_name', models.CharField(max_length=50, unique=True)),
                ('st_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_picked', models.BooleanField(default=False)),
                ('product_name', models.CharField(blank=True, max_length=50, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('brands', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.CharField(max_length=50, null=True)),
                ('code', models.IntegerField(blank=True, null=True, unique=True)),
                ('ecoscore_score', models.IntegerField(blank=True, null=True)),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=75, scale=None, size=[400, None], upload_to='stockitems/')),
                ('image_alt', models.CharField(blank=True, max_length=100, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('category_name', models.ManyToManyField(blank=True, to='stock_items.category')),
            ],
        ),
    ]
