# Generated by Django 4.2.11 on 2024-05-10 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='stock_item',
            name='category_name',
            field=models.ManyToManyField(to='stock_items.category'),
        ),
        migrations.AlterField(
            model_name='stock_item',
            name='st_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
