# Generated by Django 4.2.11 on 2024-05-11 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_items', '0002_alter_category_cat_id_alter_stock_item_category_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='cat_id',
            new_name='category_name_id',
        ),
        migrations.RemoveField(
            model_name='stock_item',
            name='category_name',
        ),
        migrations.AddField(
            model_name='stock_item',
            name='category_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock_items.category'),
        ),
    ]
